<a href="https://colab.research.google.com/github/Abhinavnair13/Playing-with-Numpy/blob/main/Learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [ ]:
b = np.array([[2.8,3.0,4],[2,4,4.2]])


array([[2.8, 3. , 4. ],
       [2. , 4. , 4.2]])

In [ ]:
b.ndim


2

In [ ]:
a.shape

(3,)

In [ ]:
b.shape


(2, 3)

In [ ]:
c= np.array([[2,3,4],[1,2,3],[1,2,4]])
c.shape

(3, 3)

In [ ]:
#get type
a.dtype


dtype('int16')

In [ ]:
#get size(16 bits(8 each))
a.itemsize

2

In [ ]:
#total size
a.itemsize*a.size
#or
a.nbytes

6

In [ ]:
b.nbytes

48

In [ ]:
d = np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])
print(d)

[[1 2 3 4 5 6 7]
 [9 8 7 6 5 4 3]]


In [ ]:
d[0][3]
d.shape

(2, 7)

In [ ]:
d[0]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
d[:,1]

array([2, 8])

In [ ]:
d.shape

(2, 7)

In [ ]:
#getting more fancy [startindex:endindex:stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [ ]:
d[1,3] =3

In [ ]:
d

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 3, 5, 4, 3]])

In [ ]:
#for every row, its 3rd column would be 2 & 9 respectively
d[:,3] =[2,9]

In [ ]:
d


array([[1, 2, 3, 2, 5, 6, 7],
       [9, 8, 7, 9, 5, 4, 3]])

In [ ]:
b  = np.array([[[1,2]]])
b.shape

(1, 1, 2)

In [ ]:
b

array([[[1, 2]]])

In [ ]:
print(b)

[[[1 2]]]


In [4]:
b= np.array([[[1,2],[8,9]],[[3,4],[5,6]]])
print(b)

[[[1 2]
  [8 9]]

 [[3 4]
  [5 6]]]


In [5]:
b.shape

(2, 2, 2)

In [7]:
b[:,1,1]

array([9, 6])

In [8]:
b[:,1,1]=([6,9])

In [9]:
b

array([[[1, 2],
        [8, 6]],

       [[3, 4],
        [5, 9]]])

In [10]:
b[:,1,:]

array([[8, 6],
       [5, 9]])

In [14]:
b[:,1,:]= [[1,2],[9,0]]

In [15]:
b


array([[[1, 2],
        [1, 2]],

       [[3, 4],
        [9, 0]]])

In [18]:
np.zeros((2,3,2),dtype='int16')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int16)

In [19]:
np.ones((4,5,2,3),dtype = 'int32')

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]], dtype=int32)

In [20]:
np.full((2,3,4),78)

array([[[78, 78, 78, 78],
        [78, 78, 78, 78],
        [78, 78, 78, 78]],

       [[78, 78, 78, 78],
        [78, 78, 78, 78],
        [78, 78, 78, 78]]])

In [22]:
np.full_like(b,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [28]:
c = np.random.randint((2,4,5),dtype='int32')
c
c

array([1, 3, 2], dtype=int32)

In [31]:
#for generating random int ,below are the parameters
d = np.random.randint(low=2,high=10,size=(3,3,3),dtype='int32')
print(d)


[[[8 2 2]
  [2 9 6]
  [9 2 3]]

 [[4 3 4]
  [3 6 3]
  [9 3 4]]

 [[4 4 3]
  [6 3 7]
  [8 4 6]]]


In [34]:
#identity matrix, by nature it is a square matrix so we only need one parameter
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
#repeating an array
#if axis = 0 , repition is done along the rows, if axis = 1 , repetition is done along columns
#repeat(which dataset u want to copy,times to copy,axis)
print(x)
r1 = np.repeat(x,3,axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
r1 = np.repeat(x,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:

# Suppose we have a 3D array with shape (2, 3, 3), representing two 3x3 matrices
matrices = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],

                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]]])

# Repeat each matrix 4 times along a new axis (axis=2)
repeated_matrices = np.repeat(matrices, repeats=4, axis=2)

print("Original array shape:\n", matrices)#2,3,3
print("Repeated array shape:\n", repeated_matrices)#2,3,4,3
#axis =0 matlab layer ke copy bane


Original array shape:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Repeated array shape:
 [[[ 1  1  1  1  2  2  2  2  3  3  3  3]
  [ 4  4  4  4  5  5  5  5  6  6  6  6]
  [ 7  7  7  7  8  8  8  8  9  9  9  9]]

 [[10 10 10 10 11 11 11 11 12 12 12 12]
  [13 13 13 13 14 14 14 14 15 15 15 15]
  [16 16 16 16 17 17 17 17 18 18 18 18]]]


In [4]:
#print this
# 11111
# 10001
# 10901
# 10001
# 11111
output = np.ones((5,5),dtype='int32')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [5]:
z = np.zeros((3,3),dtype='int32')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [6]:
z[1,1]=9

In [10]:
output[1:4,1:4]=z

In [11]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [14]:
a = np.array([1,3,4])
b=a
b[0]=100
print(a)#a=>[100,3,4]


[1 3 4]


To prevent this we have to initialize b as a copy of a


In [15]:
b=a.copy()
b[0]=100
print(a)

[1 3 4]


#Numpy Mathematics


In [16]:
a =np.array([1,2,3,4])
print(a+2)

[3 4 5 6]


In [17]:
a

array([1, 2, 3, 4])

In [18]:
a-2

array([-1,  0,  1,  2])

In [19]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [20]:
a*2

array([2, 4, 6, 8])

In [21]:
a**2

array([ 1,  4,  9, 16])

In [22]:
b =np.array([1,0,9,1])
a+b

array([ 2,  2, 12,  5])

In [23]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear algebra


In [5]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [6]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [10]:
a = np.array([[1,3,3],[4,5,6],[9,8,7]])
print(a)
det_a = np.linalg.det(a)
det_a

[[1 3 3]
 [4 5 6]
 [9 8 7]]


26.000000000000004

References - https://numpy.org/doc/stable/reference/routines.linalg.html

there are many different types of linear algebra we can perform using np linear algebra **librart**

#Statistics

In [17]:
stats = np.array([[1,2,3],[3,1,2]])
stats.min(axis=0)

array([1, 1, 2])

In [18]:
stats = np.array([[1, 2, 3], [3, 1, 2]])

min_values = stats.min(axis=0)

print(min_values)


[1 1 2]


axis=0 specifies that the minimum operation should be performed along the rows, meaning it calculates the minimum value for each column.

Here's how it works:

Along the rows axis (axis 0), NumPy considers each column separately.
For the first column [1, 3], the minimum value is 1.
For the second column [2, 1], the minimum value is 1.
For the third column [3, 2], the minimum value is 2.
So, the output [1, 1, 2] represents the minimum value for each column in the array stats, as the operation was performed along the rows (axis 0).

In [2]:


stats = np.array([[1, 2, 3], [3, 1, 2]])

min_values = stats.min(axis=1)

print(min_values)


[1 1]


In [5]:
stats.sum(axis=1)

array([6, 6])

With axis=1, the min() operation is performed along each row separately. Here's how it works:

Along the columns axis (axis 1), NumPy considers each row separately.
For the first row [1, 2, 3], the minimum value is 1.
For the second row [3, 1, 2], the minimum value is 1.
So, the output will be [1, 1], indicating the minimum value for each row in the array stats, as the operation was performed along the columns (axis 1).

#Reorganizing arrays

In [8]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
#vertically stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.vstack([v1,v2,v2,v2])
print(v3)


[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [13]:
#horizaontally stacking arrays
h1 = np.ones((2,4))
print(h1)
h2 = np.zeros((2,2))
print(h2)
h3 = np.hstack((h1,h2))
print(h3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


#Miscellaneous

In [1]:
#getting data from txt
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

NameError: name 'np' is not defined

In [7]:
#getting data from txt
filedata = np.genfromtxt('data.txt',delimiter=',',dtype ='int32')

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#Boolean masking and advanced indexing

In [8]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [9]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [10]:
#tell us if theres value greater than 50 in every column,axis =0 so row wise evaluation is done
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [12]:
np.all(filedata>50,axis=0)  #returns true if every value in the column is >50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [11]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [18]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [19]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])